# Generated by Django 4.2.11 on 2024-05-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
